# -*- coding: utf-8 -*-
"""self_pruning_network.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pxUm_sYNUZeXmvdhRype_HuFgBQ4eyU1
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim import Adam
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import numpy as np

# -------------------------------
# Part 1: Prunable Linear Layer
# -------------------------------

class PrunableLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()

        self.weight = nn.Parameter(torch.randn(out_features, in_features))
        self.bias = nn.Parameter(torch.zeros(out_features))

        # gate scores (same shape as weights)
        self.gate_scores = nn.Parameter(torch.randn(out_features, in_features))

    def forward(self, x):
        gates = torch.sigmoid(self.gate_scores)
        pruned_weights = self.weight * gates
        return F.linear(x, pruned_weights, self.bias)

# -------------------------------
# Model Definition (MLP only)
# -------------------------------

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = PrunableLinear(32*32*3, 512)
        self.fc2 = PrunableLinear(512, 256)
        self.fc3 = PrunableLinear(256, 10)

    def forward(self, x):
        x = x.view(x.size(0), -1)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# -------------------------------
# Sparsity Loss (L1 on gates)
# -------------------------------

def sparsity_loss(model):
    loss = 0
    for module in model.modules():
        if isinstance(module, PrunableLinear):
            gates = torch.sigmoid(module.gate_scores)
            loss += gates.sum()
    return loss

# -------------------------------
# Sparsity Calculation
# -------------------------------

def calculate_sparsity(model, threshold=1e-2):
    total = 0
    zero = 0

    for module in model.modules():
        if isinstance(module, PrunableLinear):
            gates = torch.sigmoid(module.gate_scores)
            total += gates.numel()
            zero += (gates < threshold).sum().item()

    return 100 * zero / total

# -------------------------------
# Evaluation
# -------------------------------

def test(model, loader):
    model.eval()
    correct = 0
    total = 0

    with torch.no_grad():
        for x, y in loader:
            outputs = model(x)
            _, pred = torch.max(outputs, 1)
            total += y.size(0)
            correct += (pred == y).sum().item()

    return 100 * correct / total

# -------------------------------
# Plot Gate Distribution
# -------------------------------

def plot_gates(model, title):
    all_gates = []

    for module in model.modules():
        if isinstance(module, PrunableLinear):
            gates = torch.sigmoid(module.gate_scores).detach().cpu().numpy().flatten()
            all_gates.extend(gates)

    plt.hist(all_gates, bins=50)
    plt.title(title)
    plt.xlabel("Gate Values")
    plt.ylabel("Frequency")
    plt.show()

# -------------------------------
# Main Training Loop
# -------------------------------

def run_experiment(lambda_val):

    transform = transforms.ToTensor()

    train_data = datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
    test_data = datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)

    train_loader = DataLoader(train_data, batch_size=64, shuffle=True)
    test_loader = DataLoader(test_data, batch_size=64)

    model = Net()
    optimizer = Adam(model.parameters(), lr=0.001)
    criterion = nn.CrossEntropyLoss()

    epochs = 5

    for epoch in range(epochs):
        model.train()

        for x, y in train_loader:
            optimizer.zero_grad()

            outputs = model(x)
            ce_loss = criterion(outputs, y)
            sp_loss = sparsity_loss(model)

            loss = ce_loss + lambda_val * sp_loss

            loss.backward()
            optimizer.step()

        print(f"Epoch {epoch+1} done")

    acc = test(model, test_loader)
    sparsity = calculate_sparsity(model)

    print(f"\nLambda: {lambda_val}")
    print(f"Accuracy: {acc:.2f}%")
    print(f"Sparsity: {sparsity:.2f}%")

    plot_gates(model, f"Lambda={lambda_val}")

    return acc, sparsity

# -------------------------------
# Run for multiple lambdas
# -------------------------------

if __name__ == "__main__":

    lambdas = [1e-5, 1e-4, 1e-3]

    results = []

    for l in lambdas:
        acc, sp = run_experiment(l)
        results.append((l, acc, sp))

    print("\nFinal Results:")
    print("Lambda | Accuracy | Sparsity")
    for r in results:
        print(f"{r[0]} | {r[1]:.2f}% | {r[2]:.2f}%")